const colorObjects = require('../styles/themes/colorObject.js');

module.exports = {
  '.text-Header': {
    fontFamily: 'Mulish',
    fontSize: '20px',
    fontWeight: 700,
    lineHeight: 1,
    letterSpacing: '-0.4px',
  },
  '.text-Title1': {
    fontFamily: 'Mulish',
    fontSize: '24px',
    fontWeight: 700,
    lineHeight: 1.5,
    letterSpacing: '-0.4px',
  },
  '.text-Title2': {
    fontFamily: 'Mulish',
    fontSize: '20px',
    fontWeight: 600,
    lineHeight: 1.5,
    letterSpacing: '-0.4px',
  },
  '.text-SubTitle': {
    fontFamily: 'Mulish',
    fontSize: '18px',
    fontWeight: 700,
    lineHeight: 1.5,
    letterSpacing: '-0.3px',
  },
  '.text-Section-Title': {
    fontFamily: 'Mulish',
    fontSize: '16px',
    fontWeight: 700,
    lineHeight: 1.5,
    letterSpacing: '-0.4px',
  },
  '.text-BlogBody1': {
    fontFamily: 'Mulish',
    fontSize: '16px',
    fontWeight: 600,
    lineHeight: 1.7,
    letterSpacing: '-0.4px',
  },
  '.text-BlogBody2': {
    fontFamily: 'Mulish',
    fontSize: '16px',
    fontWeight: 400,
    lineHeight: 1.7,
    letterSpacing: '-0.4px',
  },
  '.text-Body1': {
    fontFamily: 'Mulish',
    fontSize: '16px',
    fontWeight: 600,
    lineHeight: 1.5,
    letterSpacing: '-0.4px',
  },
  '.text-Body2': {
    fontFamily: 'Mulish',
    fontSize: '16px',
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: '-0.4px',
  },
  '.text-Body3': {
    fontFamily: 'Mulish',
    fontSize: '14px',
    fontWeight: 700,
    lineHeight: 1.5,
    letterSpacing: '-0.4px',
  },
  '.text-Body4': {
    fontFamily: 'Mulish',
    fontSize: '14px',
    fontWeight: 600,
    lineHeight: 1.5,
    letterSpacing: '-0.4px',
  },
  '.text-Body5': {
    fontFamily: 'Mulish',
    fontSize: '14px',
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: '-0.4px',
  },
  '.text-Body6': {
    fontFamily: 'Mulish',
    fontSize: '13px',
    fontWeight: 600,
    lineHeight: 1.6,
    letterSpacing: '-0.3px',
  },
  '.text-Body7': {
    fontFamily: 'Mulish',
    fontSize: '13px',
    fontWeight: 400,
    lineHeight: 1.6,
    letterSpacing: '-0.3px',
  },
  '.text-Detail1': {
    fontFamily: 'Mulish',
    fontSize: '12px',
    fontWeight: 600,
    lineHeight: 1.6,
    letterSpacing: '-0.3px',
  },
  '.text-Detail2': {
    fontFamily: 'Mulish',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 1.6,
    letterSpacing: '-0.3px',
  },
  '.text-Detail3': {
    fontFamily: 'Mulish',
    fontSize: '11px',
    fontWeight: 600,
    lineHeight: 1.6,
    letterSpacing: '-0.3px',
  },
  '.text-Line': {
    fontFamily: 'Mulish',
    fontSize: '16px',
    fontWeight: 400,
    lineHeight: 1,
    letterSpacing: '-0.4px',
  },
  '.text-Line2': {
    fontFamily: 'Mulish',
    fontSize: '14px',
    fontWeight: 500,
    lineHeight: 1,
    letterSpacing: '-0.4px',
    textDecoration: 'underline',
  },
  '.text-Score': {
    fontFamily: 'Mulish',
    fontSize: '48px',
    fontWeight: 700,
    lineHeight: 1,
    letterSpacing: '-0.6px',
  },
  '.text-Tag1': {
    fontFamily: 'GongGothicMedium',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 1,
    letterSpacing: '-0.2px',
  },
  '.text-Tag2': {
    fontFamily: 'GongGothicMedium',
    fontSize: '10px',
    fontWeight: 400,
    lineHeight: 1,
    letterSpacing: '-0.2px',
  },
};
